# Generated by Django 2.0.2 on 2018-07-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180710_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.CharField(choices=[('', 'Select Education'), ('HS', 'High School'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('', 'Select Gender'), ('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
    ]
