# Generated by Django 2.0.2 on 2018-07-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180710_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.CharField(choices=[('', 'Select Education'), ('H', 'High School'), ('U', 'Undergraduate'), ('P', 'Postgraduate')], default='', max_length=1),
        ),
    ]
