# Generated by Django 2.0.2 on 2018-07-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180713_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Email User',
                'verbose_name_plural': 'Email Users',
            },
        ),
        migrations.CreateModel(
            name='MailText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=500)),
                ('attachment', models.CharField(max_length=500)),
                ('send_it', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(to='accounts.Mail')),
            ],
            options={
                'verbose_name': 'Emails to send',
                'verbose_name_plural': 'Emails to send',
            },
        ),
    ]
