# Generated by Django 2.0.2 on 2018-07-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_mail_mailtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtext',
            name='users',
        ),
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
